# Generated by Django 5.1.6 on 2025-04-02 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meterreading',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='meterreading',
            name='is_billed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='waterrate',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='waterrate',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
